DROP DATABASE IF EXISTS BANKING;
CREATE DATABASE BANKING;

USE BANKING;

CREATE TABLE client (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(100)
);

CREATE TABLE compte_courant(
    ID_COMPTE_COURANT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    INTITULE VARCHAR(50) NOT NULL,
    SOLDE FLOAT NOT NULL,
    DECOUVERT FLOAT
);

CREATE TABLE compte_epargne(
    ID_COMPTE_EPARGNE INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    INTITULE VARCHAR(50) NOT NULL,
    SOLDE FLOAT NOT NULL,
    TAUX_INTERETS FLOAT
);

CREATE TABLE operation (
    ID_OPERATION INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPTE_DEBITE INT NOT NULL,
    ID_COMPTE_CREDITE INT NOT NULL,
    MONTANT FLOAT NOT NULL
);


INSERT INTO client (NOM, PRENOM) VALUES ('MUBOURG', 'DAXIME');
INSERT INTO compte_courant (ID_CLIENT, INTITULE, SOLDE, DECOUVERT) VALUES (1, 'Compte courant 1', 1.0, 1.0);
INSERT INTO compte_epargne (ID_CLIENT, INTITULE, SOLDE, TAUX_INTERETS) VALUES (1, 'Compte epargne 1', 15.0, 100.0);
INSERT INTO operation (ID_COMPTE_DEBITE, ID_COMPTE_CREDITE, MONTANT) VALUES(1, 2, 10.0);